### ISSUE TITLE
ylab doesn't work when `type="hist"`

### ISSUE THREAD

**Issue by jfb-h** [grantmcdermott/tinyplot#220]
Hi, 

love the package!

The y-label seems to be not set / overwritten by the default for histograms, xlab works though. MWE:

```r
plt(rnorm(1000), type="hist", ylab="")
```

**Comment by zeileis** [comment]
Great, thanks for the report. The issue has been fixed recently in #204 but not yet released to CRAN. If you install the development version, your code works as intended:

```
install.packages("tinyplot", repos = "https://grantmcdermott.R-universe.dev")
```

**Comment by martin-andresen** [comment]
I installed the latest version, but still has the same issue as this with the "density" plot type, with both x and y label.

**Comment by grantmcdermott** [comment]
@martin-andresen Hmmm, are you sure you have the latest dev version? The following examples work for me:

```r
library(tinyplot)

xx = rnorm(100)
plt(xx, type = "hist", ylab = "Hello, world!", xlab = "Here is my x-axis")
plt(xx, type = "density", ylab = "Hello, world!", xlab = "Here is my x-axis")
```

You can check your `tinyplot` version (and date stamp) as follows:

```r
packageVersion("tinyplot") 
packageDate("tinyplot")
```

And a reminder that you can grab the latest dev version with the below command (I'd recommend doing so in a fresh R session).

```r
install.packages("tinyplot", repos = "https://grantmcdermott.R-universe.dev")
```

**Comment by martin-andresen** [comment]
Thanks for the quick response, but unfortunately I still don't get x or y labels with your example code. I have confirmed that I have the latest version:

![Image](https://github.com/user-attachments/assets/10d0e602-678a-451d-8f15-bd1a2a02acd7)

R version 4.3.3, could that be it? I should update. :)

**Comment by martin-andresen** [comment]
Indeed that was the case - works with R 4.4.2.

**Comment by grantmcdermott** [comment]
> Indeed that was the case - works with R 4.4.2.

I just tested on an older version of R (using [rig](https://github.com/r-lib/rig/)) and it works for me there too. I'm trying to think of a reason why your 4.3.3 version might have been causing trouble...

Oh well, I'm glad the update on your side fixed it!
